services:
  jameslufz:
    container_name: jameslufz
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    restart: always
    environment:
      - NEXT_PUBLIC_NODE_ENV=production
      - NODE_ENV=production

networks:
  lufz-network:
    external: true