services:
  jameslufz:
    image: ghcr.io/jameslufz/jameslufz.me:latest
    container_name: jameslufz
    restart: always
    environment:
      - NEXT_PUBLIC_NODE_ENV=production
      - NODE_ENV=production
    networks:
      - lufz-network

networks:
  lufz-network:
    external: true